FROM python:3.12-slim
WORKDIR /app
RUN pip install --no-cache-dir watchfiles
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PYTHONUNBUFFERED=1
EXPOSE 8080
CMD ["python", "main.py"]
